services:
  postgres:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: finops
      POSTGRES_PASSWORD: finops
      POSTGRES_DB: finops

    ports:
      - "5432:5432"
    volumes:
      - finops_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finops -d finops"]
      interval: 5s
      retries: 10
  app:
    build: 
      context: ../..
      dockerfile: deploy/docker/Dockerfile 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/finance?sslmode=disable
    ports:
      - 10000:10000
    depends_on:
      db:
        condition: service_healthy

volumes:
  ollama:
  finops_pg_data:
  
