// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package store

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts
    (
    workspace_id,
    name,
    type,
    currency,
    opening_balance,
    opening_date
    )
VALUES
    ($1,$2,$3,$4,$5,$6)
RETURNING id, workspace_id, name, type, currency, opening_balance, opening_date, archived
`

type CreateAccountParams struct {
	WorkspaceID    int64
	Name           string
	Type           string
	Currency       string
	OpeningBalance float64
	OpeningDate    sql.NullTime
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.WorkspaceID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.OpeningBalance,
		arg.OpeningDate,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.OpeningDate,
		&i.Archived,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT
    id,
    workspace_id,
    name,
    type,
    currency,
    opening_balance,
    opening_date,
    archived
FROM accounts
WHERE 
    id = $1
AND archived = FALSE
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.OpeningDate,
		&i.Archived,
	)
	return i, err
}

const getAccountByWorkspaceAndID = `-- name: GetAccountByWorkspaceAndID :one
SELECT
    id,
    workspace_id,
    name,
    type,
    currency,
    opening_balance,
    opening_date,
    archived
FROM accounts
WHERE workspace_id = $1
    AND id = $2
    AND archived = FALSE
`

type GetAccountByWorkspaceAndIDParams struct {
	WorkspaceID int64
	ID          int64
}

func (q *Queries) GetAccountByWorkspaceAndID(ctx context.Context, arg GetAccountByWorkspaceAndIDParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByWorkspaceAndID, arg.WorkspaceID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.OpeningDate,
		&i.Archived,
	)
	return i, err
}

const listAccountsByWorkspace = `-- name: ListAccountsByWorkspace :many
SELECT
    id,
    workspace_id,
    name,
    type,
    currency,
    opening_balance,
    opening_date,
    archived
FROM accounts 
WHERE workspace_id = $1 
    AND archived = FALSE
ORDER BY name ASC
`

func (q *Queries) ListAccountsByWorkspace(ctx context.Context, workspaceID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.OpeningBalance,
			&i.OpeningDate,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET
    name = $3,
    type = $4,
    currency = $5,
    opening_balance = $6,
    opening_date = $7
WHERE workspace_id = $1
    AND id = $2
    AND archived = FALSE
RETURNING id, workspace_id, name, type, currency, opening_balance, opening_date, archived
`

type UpdateAccountParams struct {
	WorkspaceID    int64
	ID             int64
	Name           string
	Type           string
	Currency       string
	OpeningBalance float64
	OpeningDate    sql.NullTime
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.OpeningBalance,
		arg.OpeningDate,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.OpeningBalance,
		&i.OpeningDate,
		&i.Archived,
	)
	return i, err
}
