// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package store

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    workspace_id,
    parent_id,
    name, 
    kind
) VALUES ($1,$2,$3,$4) RETURNING 
    id,
    workspace_id,
    parent_id,
    name,
    kind,
    archived
`

type CreateCategoryParams struct {
	WorkspaceID int64
	ParentID    sql.NullInt64
	Name        string
	Kind        string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Kind,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.Archived,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories SET archived = true WHERE workspace_id = $1 AND id = $2
`

type DeleteCategoryParams struct {
	WorkspaceID int64
	ID          int64
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.WorkspaceID, arg.ID)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT 
    id,
    workspace_id,
    parent_id,
    name,
    kind,
    archived
FROM categories WHERE archived = false AND workspace_id=$1 ORDER BY name ASC
`

func (q *Queries) GetCategories(ctx context.Context, workspaceID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByWorkspaceAndID = `-- name: GetCategoryByWorkspaceAndID :one
SELECT
    id,
    workspace_id,
    parent_id,
    name,
    kind,
    archived
FROM categories
WHERE archived = false
    AND workspace_id = $1
    AND id = $2
`

type GetCategoryByWorkspaceAndIDParams struct {
	WorkspaceID int64
	ID          int64
}

func (q *Queries) GetCategoryByWorkspaceAndID(ctx context.Context, arg GetCategoryByWorkspaceAndIDParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByWorkspaceAndID, arg.WorkspaceID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.Archived,
	)
	return i, err
}

const getCategoryByWorkspaceAndName = `-- name: GetCategoryByWorkspaceAndName :one
SELECT
    id,
    workspace_id,
    parent_id,
    name,
    kind,
    archived
FROM categories
WHERE workspace_id = $1
    AND name = $2
`

type GetCategoryByWorkspaceAndNameParams struct {
	WorkspaceID int64
	Name        string
}

func (q *Queries) GetCategoryByWorkspaceAndName(ctx context.Context, arg GetCategoryByWorkspaceAndNameParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByWorkspaceAndName, arg.WorkspaceID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.Archived,
	)
	return i, err
}

const unarchiveCategory = `-- name: UnarchiveCategory :exec
UPDATE categories SET archived = false WHERE workspace_id = $1 AND name = $2
`

type UnarchiveCategoryParams struct {
	WorkspaceID int64
	Name        string
}

func (q *Queries) UnarchiveCategory(ctx context.Context, arg UnarchiveCategoryParams) error {
	_, err := q.db.ExecContext(ctx, unarchiveCategory, arg.WorkspaceID, arg.Name)
	return err
}
