// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projections.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createCommitment = `-- name: CreateCommitment :one
INSERT INTO commitments (
    workspace_id,
    account_id,
    name,
    kind,
    monthly_value,
    start_month,
    end_month,
    notes
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, workspace_id, account_id, name, kind, monthly_value, start_month, end_month, notes, created_at
`

type CreateCommitmentParams struct {
	WorkspaceID  int64
	AccountID    sql.NullInt64
	Name         string
	Kind         string
	MonthlyValue string
	StartMonth   time.Time
	EndMonth     sql.NullTime
	Notes        sql.NullString
}

func (q *Queries) CreateCommitment(ctx context.Context, arg CreateCommitmentParams) (Commitment, error) {
	row := q.db.QueryRowContext(ctx, createCommitment,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Name,
		arg.Kind,
		arg.MonthlyValue,
		arg.StartMonth,
		arg.EndMonth,
		arg.Notes,
	)
	var i Commitment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Kind,
		&i.MonthlyValue,
		&i.StartMonth,
		&i.EndMonth,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommitment = `-- name: DeleteCommitment :exec
DELETE FROM commitments WHERE workspace_id = $1 AND id = $2
`

type DeleteCommitmentParams struct {
	WorkspaceID int64
	ID          int64
}

func (q *Queries) DeleteCommitment(ctx context.Context, arg DeleteCommitmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommitment, arg.WorkspaceID, arg.ID)
	return err
}

const deleteVariableExpenseOverride = `-- name: DeleteVariableExpenseOverride :exec
DELETE FROM variable_expense_overrides WHERE workspace_id = $1 AND month = $2
`

type DeleteVariableExpenseOverrideParams struct {
	WorkspaceID int64
	Month       time.Time
}

func (q *Queries) DeleteVariableExpenseOverride(ctx context.Context, arg DeleteVariableExpenseOverrideParams) error {
	_, err := q.db.ExecContext(ctx, deleteVariableExpenseOverride, arg.WorkspaceID, arg.Month)
	return err
}

const findSimilarTransactions = `-- name: FindSimilarTransactions :many
SELECT id, posted_on, description, amount, direction
FROM transactions
WHERE workspace_id = $1
  AND account_id = $2
  AND amount = $3
  AND posted_on BETWEEN $4 AND $5
`

type FindSimilarTransactionsParams struct {
	WorkspaceID int64
	AccountID   int64
	Amount      string
	PostedOn    time.Time
	PostedOn_2  time.Time
}

type FindSimilarTransactionsRow struct {
	ID          int64
	PostedOn    time.Time
	Description string
	Amount      string
	Direction   string
}

func (q *Queries) FindSimilarTransactions(ctx context.Context, arg FindSimilarTransactionsParams) ([]FindSimilarTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, findSimilarTransactions,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Amount,
		arg.PostedOn,
		arg.PostedOn_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSimilarTransactionsRow
	for rows.Next() {
		var i FindSimilarTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostedOn,
			&i.Description,
			&i.Amount,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommitmentByWorkspaceAndID = `-- name: GetCommitmentByWorkspaceAndID :one
SELECT id, workspace_id, account_id, name, kind, monthly_value, start_month, end_month, notes, created_at
FROM commitments
WHERE workspace_id = $1 AND id = $2
`

type GetCommitmentByWorkspaceAndIDParams struct {
	WorkspaceID int64
	ID          int64
}

func (q *Queries) GetCommitmentByWorkspaceAndID(ctx context.Context, arg GetCommitmentByWorkspaceAndIDParams) (Commitment, error) {
	row := q.db.QueryRowContext(ctx, getCommitmentByWorkspaceAndID, arg.WorkspaceID, arg.ID)
	var i Commitment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.Kind,
		&i.MonthlyValue,
		&i.StartMonth,
		&i.EndMonth,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectionSettings = `-- name: GetProjectionSettings :one
SELECT workspace_id, monthly_income, variable_expense, opening_balance, horizon_start,
    property_value, down_payment_monthly, down_payment_months, financing_annual_rate,
    financing_term_years, share_pct, updated_at
FROM projection_settings
WHERE workspace_id = $1
`

func (q *Queries) GetProjectionSettings(ctx context.Context, workspaceID int64) (ProjectionSetting, error) {
	row := q.db.QueryRowContext(ctx, getProjectionSettings, workspaceID)
	var i ProjectionSetting
	err := row.Scan(
		&i.WorkspaceID,
		&i.MonthlyIncome,
		&i.VariableExpense,
		&i.OpeningBalance,
		&i.HorizonStart,
		&i.PropertyValue,
		&i.DownPaymentMonthly,
		&i.DownPaymentMonths,
		&i.FinancingAnnualRate,
		&i.FinancingTermYears,
		&i.SharePct,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommitments = `-- name: ListCommitments :many
SELECT
    c.id,
    c.workspace_id,
    c.account_id,
    c.name,
    c.kind,
    c.monthly_value,
    c.start_month,
    c.end_month,
    c.notes,
    a.name AS account_name
FROM commitments c
LEFT JOIN accounts a ON a.id = c.account_id
WHERE c.workspace_id = $1
ORDER BY c.start_month, c.name
`

type ListCommitmentsRow struct {
	ID           int64
	WorkspaceID  int64
	AccountID    sql.NullInt64
	Name         string
	Kind         string
	MonthlyValue string
	StartMonth   time.Time
	EndMonth     sql.NullTime
	Notes        sql.NullString
	AccountName  sql.NullString
}

func (q *Queries) ListCommitments(ctx context.Context, workspaceID int64) ([]ListCommitmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommitments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommitmentsRow
	for rows.Next() {
		var i ListCommitmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.Kind,
			&i.MonthlyValue,
			&i.StartMonth,
			&i.EndMonth,
			&i.Notes,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariableExpenseOverrides = `-- name: ListVariableExpenseOverrides :many
SELECT workspace_id, month, value
FROM variable_expense_overrides
WHERE workspace_id = $1
ORDER BY month
`

func (q *Queries) ListVariableExpenseOverrides(ctx context.Context, workspaceID int64) ([]VariableExpenseOverride, error) {
	rows, err := q.db.QueryContext(ctx, listVariableExpenseOverrides, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariableExpenseOverride
	for rows.Next() {
		var i VariableExpenseOverride
		if err := rows.Scan(&i.WorkspaceID, &i.Month, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommitment = `-- name: UpdateCommitment :exec
UPDATE commitments SET
    account_id = $3,
    name = $4,
    kind = $5,
    monthly_value = $6,
    start_month = $7,
    end_month = $8,
    notes = $9
WHERE workspace_id = $1 AND id = $2
`

type UpdateCommitmentParams struct {
	WorkspaceID  int64
	ID           int64
	AccountID    sql.NullInt64
	Name         string
	Kind         string
	MonthlyValue string
	StartMonth   time.Time
	EndMonth     sql.NullTime
	Notes        sql.NullString
}

func (q *Queries) UpdateCommitment(ctx context.Context, arg UpdateCommitmentParams) error {
	_, err := q.db.ExecContext(ctx, updateCommitment,
		arg.WorkspaceID,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Kind,
		arg.MonthlyValue,
		arg.StartMonth,
		arg.EndMonth,
		arg.Notes,
	)
	return err
}

const upsertProjectionSettings = `-- name: UpsertProjectionSettings :one
INSERT INTO projection_settings (
    workspace_id, monthly_income, variable_expense, opening_balance, horizon_start,
    property_value, down_payment_monthly, down_payment_months, financing_annual_rate,
    financing_term_years, share_pct, updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11, now())
ON CONFLICT (workspace_id) DO UPDATE SET
    monthly_income = EXCLUDED.monthly_income,
    variable_expense = EXCLUDED.variable_expense,
    opening_balance = EXCLUDED.opening_balance,
    horizon_start = EXCLUDED.horizon_start,
    property_value = EXCLUDED.property_value,
    down_payment_monthly = EXCLUDED.down_payment_monthly,
    down_payment_months = EXCLUDED.down_payment_months,
    financing_annual_rate = EXCLUDED.financing_annual_rate,
    financing_term_years = EXCLUDED.financing_term_years,
    share_pct = EXCLUDED.share_pct,
    updated_at = now()
RETURNING workspace_id, monthly_income, variable_expense, opening_balance, horizon_start,
    property_value, down_payment_monthly, down_payment_months, financing_annual_rate,
    financing_term_years, share_pct, updated_at
`

type UpsertProjectionSettingsParams struct {
	WorkspaceID         int64
	MonthlyIncome       string
	VariableExpense     string
	OpeningBalance      string
	HorizonStart        sql.NullTime
	PropertyValue       string
	DownPaymentMonthly  string
	DownPaymentMonths   int32
	FinancingAnnualRate string
	FinancingTermYears  int32
	SharePct            string
}

func (q *Queries) UpsertProjectionSettings(ctx context.Context, arg UpsertProjectionSettingsParams) (ProjectionSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertProjectionSettings,
		arg.WorkspaceID,
		arg.MonthlyIncome,
		arg.VariableExpense,
		arg.OpeningBalance,
		arg.HorizonStart,
		arg.PropertyValue,
		arg.DownPaymentMonthly,
		arg.DownPaymentMonths,
		arg.FinancingAnnualRate,
		arg.FinancingTermYears,
		arg.SharePct,
	)
	var i ProjectionSetting
	err := row.Scan(
		&i.WorkspaceID,
		&i.MonthlyIncome,
		&i.VariableExpense,
		&i.OpeningBalance,
		&i.HorizonStart,
		&i.PropertyValue,
		&i.DownPaymentMonthly,
		&i.DownPaymentMonths,
		&i.FinancingAnnualRate,
		&i.FinancingTermYears,
		&i.SharePct,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVariableExpenseOverride = `-- name: UpsertVariableExpenseOverride :exec
INSERT INTO variable_expense_overrides (workspace_id, month, value)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, month) DO UPDATE SET value = EXCLUDED.value
`

type UpsertVariableExpenseOverrideParams struct {
	WorkspaceID int64
	Month       time.Time
	Value       string
}

func (q *Queries) UpsertVariableExpenseOverride(ctx context.Context, arg UpsertVariableExpenseOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertVariableExpenseOverride, arg.WorkspaceID, arg.Month, arg.Value)
	return err
}
